[package]
name = "tracking-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { workspace = true, features = ["cubecl", "wgpu", "autodiff"] }
crossbeam = "0.8.4"
parking_lot = "0.12.5"
rusqlite.workspace = true
serde_json.workspace = true
sha2 = "0.10.9"
