[workspace]
resolver = "3"
members = ["isthatarock/handwritten/handwritten-model", "isthatarock/handwritten/handwritten-training"]

[workspace.dependencies]
rustc-hash = "2.1.1"
burn = { version = "0.18", features = ["std", "wgpu", "fusion", "accelerate", "openblas"], default-features = false }
rand = { version = "0.9.2", features = ["small_rng"], default-features = false }
image = "0.24"
serde = { version = "1.0.226", features = ["derive"] }
