[package]
name = "general-dataset"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite.workspace = true
# lru = "0.16.1"
# rustc-hash.workspace = true
thiserror.workspace = true
burn.workspace = true
image.workspace = true
rayon.workspace = true
rand.workspace = true