[package]
name = "proximo"
version = "0.1.0"
edition = "2024"

[dependencies]
general-models.workspace = true
general-dataset.workspace = true
burn = { workspace = true, features = [] }
image = { workspace = true, features = ["webp"] }
utils = { workspace = true, optional = true }
clap = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
quanta = "0.12.6"
serde.workspace = true
serde_json = { workspace = true, optional = true }
rayon.workspace = true
rusqlite.workspace = true

[features]
wgpu = ["general-models/wgpu"]
rocm = ["general-models/rocm"]
cuda = ["general-models/cuda"]
app = ["utils", "clap", "rand"]
default = ["app", "wgpu"]
macos = ["general-models/macos"]