[package]
name = "handwritten-dataset"
version = "0.1.0"
edition = "2024"

[dependencies]
image = { workspace = true }
rusqlite = { version = "0.37.0", features = ["bundled"] }
rayon = "1.11.0"
crossbeam = "0.8.4"
hex = "0.4.3"
sha2 = "0.10.9"
rand.workspace = true
rand_distr = "0.5.1"